.PHONY: nodejs/install
## Install NodeJS
nodejs/install:
	@curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
	@sudo bash /tmp/nodesource_setup.sh
	@sudo apt update
	@sudo apt install --yes nodejs
